# Generated by Django 3.2.12 on 2022-12-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='inactivated',
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='url',
            field=models.URLField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
