# Generated by Django 3.2.12 on 2022-12-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20221214_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='inactivated',
            new_name='completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='url',
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
